### ISSUE TITLE
ST3 problem ?

### ISSUE THREAD

**Issue by wookiesh** [adamlilienfeldt/Sublime-Gitignore#6]
Got a 

``` python
y/Application Support/Sublime Text 3/Packages/User/Default (OSX).sublime-keymap with encoding UTF-8 (atomic)
found 14 files for base name Default.sublime-keymap
Traceback (most recent call last):
  File "/Users/joseph/Library/Application Support/Sublime Text 3/Packages/GitIgnore/gitignore.py", line 77, in second_select
    self.write_file()
  File "/Users/joseph/Library/Application Support/Sublime Text 3/Packages/GitIgnore/gitignore.py", line 88, in write_file
    text = self._loadfile(bp + ".gitignore")
  File "/Users/joseph/Library/Application Support/Sublime Text 3/Packages/GitIgnore/gitignore.py", line 47, in _loadfile
    text = f.read().decode()
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by alfredbez** [comment]
some error here
ST3 (Build 3064)
Mac OS X 10.9

**Comment by wookiesh** [comment]
Guess that's old enough to close :)
